[package]
name = "packetcrypt"
version = "0.1.0"
authors = ["Caleb James DeLisle <cjd@cjdns.fr>"]
edition = "2018"

[dev-dependencies]
hex-literal = "0.3"

[dependencies]
tokio = { version = "0.2", features = ["macros","sync","fs"] }
warp = "0.2"
reqwest = { version = "0.10", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
bytes = "0.5"
anyhow = "1.0"
blake2b_simd = "0.5"
hex = "0.4"
packetcrypt-sys = { version = "0.1", path = "packetcrypt-sys" }
derivative = "2.1"
rand = "0.7"
crossbeam-channel = "0.4"
regex = "1"
log = "0.4"
env_logger = "0.7"
futures-core = "0.3"
sha2 = "0.9"