[package]
name = "packetcrypt"
version = "0.1.2"
authors = ["Caleb James DeLisle <cjd@cjdns.fr>"]
edition = "2018"
license = "LGPL-2.1-only OR LGPL-3.0-only"
description = """
PacketCrypt proof of work algorithm
"""

[dev-dependencies]
hex-literal = "0.3"

[dependencies]
tokio = { version = "0.2", features = ["macros","sync","fs"], default-features = false }
warp = { version = "0.2", features = [], default-features = false }
reqwest = { version = "0.10", features = ["stream"], default-features = false }
serde = { version = "1.0", features = ["derive"], default-features = false }
serde_json = "1.0"
toml = "0.5"
bytes = "0.5"
anyhow = "1.0"
blake2b_simd = "0.5"
hex = "0.4"
packetcrypt-sys = { version = "0.2", path = "packetcrypt-sys" }
rand = "0.7"
crossbeam-channel = "0.4"
regex = "1"
log = "0.4"
env_logger = "0.7"
sha2 = "0.9"
clap = "2.33"
num_cpus = "1.13"